### PR TITLE
Usability/collapsible headings

### PR DESCRIPTION
**Pull request by Kevin-McIsaac**
I'm a git noob. What do I need to do to install your changes so I can view/test these features?

### CODE REVIEW

**Comment by Kevin-McIsaac** [comment]
I sorted out how to install these changes and have used this for about an hour of work. The new selection method, i.e., click on the heading group bar to select all cells, is fantastic. Now that I'm clicking and double clicking the heading cell bars a lot more, I'm finding this a little difficult. 

I'm not sure if its the lack of feedback when I roll over the bar or the width of the slection area.   Two thoughts that might help are:
1 Highlight the bar when the mouse rolls over its selection area, i.e., as is done with other controls such as buttons. 
2. Make the selection area (not the line) slightly bigger, though this might require greater separation of the bars.

**Comment by Kevin-McIsaac** [comment]
I try to change the default heading selection action, i.e.,  reveal the children, using the config. When I went to the config panel instead of a checkbox for this feature it showed a key binding which seems wrong.
unnamed image

http://goo.gl/80KyBI

**Comment by jcb91** [comment]
So i guess you sorted the git? Ah, sorry, that's probably a bug, I've made
a mistake with the yaml file copying and pasting!

**Comment by jcb91** [comment]
Ah, sorry, I missed a comment there. Ok, so the clicking bars is a bit
fiddly. A hover highlight is a good idea, I'll add that later today. Making
them wider is also possible, I just kept them quite narrow for now because
of the space they take up, which is subtracted from the cell width. Maybe
the width could be configurable, even, to accommodate users on both narrow
and wide displays...

**Comment by Kevin-McIsaac** [comment]
This is looking and working great! The hover highlight for the heading brackets greatly improves usability as it provides the necessary visual feedback. This is working so well that I've gotten rid of the arrow on the left and just use the brackets. 

A couple more thoughts to tune this:
1. When a bracket has been selected, i.e., to select all the child cells, rather than highlighting all the cells, just highlighting the selected bracket in the same colour as the cell selection highlight (i.e., #42A5F5) and change the right border width to 3px. This clearly show which heading level has been selected and might look cleaner than highlighting all cell. 
2. Change the hover colour/width to match selection, i.e., same as above. This improves the selection feedback. 
3. You might add hover css for .chb-start and end so the cell bracket tops/bottoms don't disappear on hover.

**Comment by jcb91** [comment]
For 1, I'm reluctant to alter the existing css for showing selected cells (which is where the highlighting comes from, that's base Jupyter behaviour for multi-cell selections). It might make sense if you select only a bracket, but if your selection also includes things outside that bracket (as when you have something selected, then shift-click a bracket), it isn't obvious to me what a new user should expect to see, given the existing notebook behaviour. It would be easy enough to change the colour of _all_ brackets on a selected cell with a simple css rule, but that isn't really the same thing, would probably be more confusing rather than less, and doesn't work for cells which don't have a bracket. The most sensible solution I can think of would be for brackets to change colour only if _all_ the cells in the corresponding section are selected, but that means recolouring all the brackets in the whole _notebook _ every time the selection changes, which might turn out to be a bit much. I can't really say I'm up for writing the logic for that right now. Maybe in future if it seems like a particularly popular thing, and the notebook css doesn't change too much!

In 2., I see what you mean about hover colour, but not hover width. Do you mean make the bracket lines thicker for brackets which are selected, similar to collapsed heading brackets, something like that?

For 3, your bracket tops and bottoms disappear on hover? Mine don't seem to - could you post a picture?

**Comment by Kevin-McIsaac** [comment]
Reg "bracket tops and bottoms disappear on hover" - I checked again and I was wrong.

**Comment by Kevin-McIsaac** [comment]
Re: "hover width. Do you mean make the bracket lines thicker for brackets which are selected" 
Yes

**Comment by Kevin-McIsaac** [comment]
Item #1 - I didn't explain very well. I think we are saying the same thing.... That is, when I 
1. **select a bracket**, the selected bracket changes colour and line width  (I think to match the hover). This shows that you've selected a set of cells in a heading group.
2. **select a few cells**, the brackets don't change

I tried to draw it like this
unnamed image 1

**Comment by jcb91** [comment]
Ah, it seems your image has had the vital brackets cropped off :confused:

**Comment by Kevin-McIsaac** [comment]
Oops
unnamed image 3

**Pull request closed without merging**
